config/routes.rb
Rails.application.routes.draw do
  root "boards#index"

  devise_for :users do
    resources :boards
  end

  resources :boards do
    resources :lists
  end

  resources :lists do
    resources :cards
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user, optional: true
  has_many :lists, dependent: :destroy
  validates :name, presence: true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list, optional: true
  validates :title, presence: true
  validates :priority, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board, optional: true
  has_many :cards, dependent: :destroy
  validates :priority, presence: true
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boards

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @boards = current_user.boards
  end

  def show
    @lists = @board.lists.all
  end

  def new
    @board = current_user.boards.new
  end

  def create
    @board = current_user.boards.create(board_params)
    if @board.save
      flash[:success] = "Board Created"
      redirect_to @board
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      flash[:success] = "Board Updated"
      redirect_to @board
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    flash[:success] = "Board Deleted"
    redirect_to root_path
  end

  private

  def board_params
    params.require(:board).permit(:name, :user_id)
  end

  def set_board
    @board = current_user.boards.find(params[:id])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_list
  before_action :set_card, only: [:edit, :update, :destroy]

  def index
    @cards = @list.cards.new
  end

  def new
    @card = Card.new
  end

  def create
    @list.cards.create(card_params)
    redirect_to board_path(@list.board_id)
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to board_path(@list.board_id)
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to board_path(@list.board_id)
  end

  private

  def set_card
    @card = Card.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def card_params
    params.require(:card).permit(:title, :description, :priority)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board, only: [:new, :create, :edit, :update]
  before_action :set_list, only: [:edit, :update, :destroy]

  def new
    @list = @board.lists.new
  end

  def create
    @list = @board.lists.new(list_params)
    if @list.save
      redirect_to @board
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to @board
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to board_path(@list.board_id)
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def set_board
    @board = Board.find(params[:board_id])
  end

  def list_params
    params.require(:list).permit(:title, :priority)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label "Board Name" %>
    <%= f.text_field :name, required: true, class: "input"%>
  </div>
  <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit Board</h1>

<%= render "form" %>

app/views/boards/index.html.erb
<h1><%= current_user.first_name %>'s Boards</h1>
<%= link_to 'New Board', new_board_path, class:"ui green button inverted" %>
<div class="ui divider"></div>
<h2><%= @boards.length <= 0 ? "No Boards - Add One" : "" %></h2>
  <div class="ui grid">
  <% @boards.each do |board| %>
  <div class="three wide column">
  <div class="ui raised center aligned segment">
      <h3><%= link_to board.name, board_path(board)%></h3> 
      <%= link_to "Delete Board", board, method: :delete, class: "ui red mini button inverted" %>
       </div>
    </div>
  <% end %>
</div>
 

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render "form" %>

app/views/boards/show.html.erb
<h1 class="ui header"><%= @board.name %></h1>
<%= link_to "Edit Board", edit_board_path(@board), class: "ui orange button inverted" %>
<%= link_to "Delete Board", @board, method: :delete, class: "ui red button inverted" %>
<%= link_to 'New List', new_board_list_path(@board), class: "ui green button inverted" %>
<div class="ui divider"></div>

<div class="ui three column grid">
  <% @board.lists.sort_by(&:priority).each do |list| %>
  <div class="column">
    <div class="ui fluid card">
      <div class="ui raised center aligned segment">
        <h3><%= list.title %></h3>
      
        <%= link_to 'New Card', new_list_card_path(list), class:"ui mini green button inverted" %>
        <div class="ui divider"></div>
          <% list.cards.sort_by(&:priority).each do |card| %>
          <div class="five wide column">
            <div class="ui raised center aligned segment">
              <h3><%= card.title%></h3>
              <div class="ui divider"></div>
              <p><%= card.description%></p>
              <%= link_to "Edit Card", edit_list_card_path(list, card), class: "ui mini orange button inverted" %>
              <%= link_to "Delete Card", list_card_path(list, card), method: :delete, class: "ui mini red button inverted" %>
                </div>
              </div>
            <%end%>
            <div class="ui divider"></div>
          <%= link_to "Edit List", edit_board_list_path(@board, list), class: "ui mini orange button inverted" %>
          <%= link_to "Delete List", list, method: :delete, class: "ui mini red button inverted" %>
              </div>
      </div>
    </div>
  <% end %>
</div>
<br>
<br>

app/views/cards/_form.html.erb
  <%= form_with(model: [@list, @card], local: true, class: "ui form") do |f| %>
    <div class="field">
      <%= f.label "Card Title" %>
      <%= f.text_field :title, required: true, class: "input" %>
    </div>
    <div class="field">
      <%= f.label "Description" %>
      <%= f.text_field :description, class: "input" %>
    </div>
    <div class="field">
      <%= f.label "Priority" %>
      <%= f.number_field :priority, required: true, class: "input" %>
    </div>
  <%= f.submit nil, class: "ui blue button" %>
<%end%>

app/views/cards/edit.html.erb
<h1>Cards#edit</h1>
<p>Find me in app/views/cards/edit.html.erb</p>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render "form" %>

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
    <% if current_user %>
      <%= link_to 'Boards Home', boards_path, class: "item"%>
      <div class="right menu">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "item" %>
      </div>
    <% else %>
      <div class="right menu">
          <%= link_to "Login", new_user_session_path, class: "item" %>
          <%= link_to "Register", new_user_registration_path, class: "item" %>
      </div>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
      <%= render "layouts/navbar" %>
      <div class="ui container">
          <%= yield %>
      </div>  
    </body>
</html>

app/views/lists/_form.html.erb
  <%= form_with(model: [@board, @list], local: true, class: "ui form") do |f| %>
    <div class="field">
      <%= f.label "List Title" %>
      <%= f.text_field :title, required: true, class: "input" %>
    </div>
    <div class="field">
      <%= f.label "Priority" %>
      <%= f.number_field :priority, required: true, class: "input" %>
    </div>
  <%= f.submit nil, class: "ui blue button" %>
  <% end %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= render "form" %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render "form" %>